version: "3.9"
services:
  drupal:
    build: 
      context: . 
      dockerfile: drupal/Dockerfile
    image: krstphr/custom_drupal:latest
    ports:
      - 8083:80 
    container_name: drupal
    volumes:
      - drupal_test4_modules:/var/www/html/modules
      - drupal_test4_profiles:/var/www/html/profiles
      - drupal_test4_themes:/var/www/html/themes
      - drupal_test4_sites:/var/www/html/sites
      - ./exports:/testdir
      - ./exports/custom
    restart: always 
    
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    container_name: mysql
    volumes:
      - drupal_test4_dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DR_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USR}
      - MYSQL_PASSWORD=${MYSQL_PW}
volumes:
  drupal_test4_modules:
  drupal_test4_profiles:
  drupal_test4_themes:
  drupal_test4_sites:
  drupal_test4_dbdata: